// Stampa le potenze di 2 senza superare il numero 1000

// IL RISULTATO DELLA POTENZA NON DEVE SUPERARE 1000

var array = [0];
var result = 0;

/*
ATTENZIONE!! SE IMPOSTO RESULT < 1000 SUPERERO' IL 1000 IN QUANTO SI ACCORGE SOLO UNA VOLTA CHE L'HA SUPERATO (PERCHE' QUANDO ARRIVA VICINO AL 1000 STA ANDANDO PRATICAMENTE DI 30 IN 30 ) QUINDI LO SUPERA PER FORZA NON RIESCE A BLOCCARSI PRIMA.
SE STESSIMO CONTANDO DI 1 IN 1 ALLORA SI SAREBBE FERMATO A 1000 GIUSTO.
IN QUESTO CASO L'UNICA SOLUZINE CHE MI VIENE AL MOMENTO è IMPOSTARE RESULT < DI 960 IN QUANTO COSI' SI FERMA ALL'ULTIMO "BRAKE POINT" PRIMA DEL 1000
*/
for (var i = 0; i < array.length && result < 960; i++) {
    result = [i] * [i];
    array.push(result);
    console.log(result);
}
